const constants = {
    COMMENTS_HAVE_ERRORED: 'COMMENTS_HAVE_ERRORED',
    COMMENTS_ARE_LOADING: 'COMMENTS_ARE_LOADING',
    COMMENTS_FETCH_DATA_SUCCESS: 'COMMENTS_FETCH_DATA_SUCCESS',
    ADD_COMMENT: 'ADD_COMMENT',
    ADD_USER: 'ADD_USER',
    USERS_HAVE_ERRORED: 'USERS_HAVE_ERRORED',
    USERS_ARE_LOADING: 'USERS_ARE_LOADING',
    USERS_FETCH_DATA_SUCCESS: 'USERS_FETCH_DATA_SUCCESS'
}

export default constants